from app.models import db, SpecialInterest


def seed_special_interests():
    demo2_1 = SpecialInterest(user_id=2, name='Climbing')
    demo2_2 = SpecialInterest(user_id=2, name='Reading')
    demo2_3 = SpecialInterest(user_id=2, name='Kayaking')
    demo2_4 = SpecialInterest(user_id=2, name='Hiking')
    demo2_5 = SpecialInterest(user_id=2, name='Swimming')
    james1 = SpecialInterest(user_id=5, name='Guitar')
    brendon1 = SpecialInterest(user_id=6, name='Video Games')
    brendon2 = SpecialInterest(user_id=6, name='Reading')
    brendon3 = SpecialInterest(user_id=6, name='Hiking')
    katerina1 = SpecialInterest(user_id=7, name='Travelling')
    joan1 = SpecialInterest(user_id=8, name='Reading')
    joan2 = SpecialInterest(user_id=8, name='Crossword Puzzles')
    joan3 = SpecialInterest(user_id=8, name='Skiing')
    joan4 = SpecialInterest(user_id=8, name='Hiking')
    joan5 = SpecialInterest(user_id=8, name='Running')
    joan6 = SpecialInterest(user_id=8, name='Anything outside :)')
    whit1 = SpecialInterest(user_id=9, name='Art')
    whit2 = SpecialInterest(user_id=9, name='Printmaking')
    whit3 = SpecialInterest(user_id=9, name='Woodblock Printing')
    whit4 = SpecialInterest(user_id=9, name='Watercolor/Gouache')
    whit5 = SpecialInterest(user_id=9, name='Legend of Zelda')
    whit6 = SpecialInterest(user_id=9, name='Video Games')
    whit7 = SpecialInterest(user_id=9, name='Welding')
    whit8 = SpecialInterest(user_id=9, name='Travel')
    whit9 = SpecialInterest(user_id=9, name='Eating Food')
    whit10 = SpecialInterest(user_id=9, name='Cooking Food')
    john1 = SpecialInterest(user_id=10, name='Skiing')
    john2 = SpecialInterest(user_id=10, name='TV Shows')
    john3 = SpecialInterest(user_id=10, name='All Movies')
    leonel1 = SpecialInterest(user_id=11, name='Working Out')
    leonel2 = SpecialInterest(user_id=11, name='Taking care of plants')
    leonel3 = SpecialInterest(user_id=11, name='Hanging out with friends')
    david1 = SpecialInterest(user_id=12, name='Drawing')
    david2 = SpecialInterest(user_id=12, name='Reading')
    david3 = SpecialInterest(user_id=12, name='Coding')
    david4 = SpecialInterest(user_id=12, name='Warm Weather')
    david5 = SpecialInterest(user_id=12, name='Dogs')
    vern1 = SpecialInterest(user_id=13, name='Huge Tech')
    vern2 = SpecialInterest(user_id=13, name='Anime')
    vern3 = SpecialInterest(user_id=13, name='Spots')
    vern4 = SpecialInterest(user_id=13, name='Coding')


    db.session.add(demo2_1)
    db.session.add(demo2_2)
    db.session.add(demo2_3)
    db.session.add(demo2_4)
    db.session.add(demo2_5)
    db.session.add(james1)
    db.session.add(brendon1)
    db.session.add(brendon2)
    db.session.add(brendon3)
    db.session.add(katerina1)
    db.session.add(joan1)
    db.session.add(joan2)
    db.session.add(joan3)
    db.session.add(joan4)
    db.session.add(joan5)
    db.session.add(joan6)
    db.session.add(whit1)
    db.session.add(whit2)
    db.session.add(whit3)
    db.session.add(whit4)
    db.session.add(whit5)
    db.session.add(whit6)
    db.session.add(whit7)
    db.session.add(whit8)
    db.session.add(whit9)
    db.session.add(whit10)
    db.session.add(john1)
    db.session.add(john2)
    db.session.add(john3)
    db.session.add(leonel1)
    db.session.add(leonel2)
    db.session.add(leonel3)
    db.session.add(david1)
    db.session.add(david2)
    db.session.add(david3)
    db.session.add(david4)
    db.session.add(david5)
    db.session.add(vern1)
    db.session.add(vern2)
    db.session.add(vern3)
    db.session.add(vern4)

    db.session.commit()


def undo_special_interests():
    db.session.execute('TRUNCATE special_interests RESTART IDENTITY CASCADE;')
    db.session.commit()
