"""create favorite stim aids table

Revision ID: d913c37df9cf
Revises: 76cd32cb1bb7
Create Date: 2022-04-17 23:44:42.382205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd913c37df9cf'
down_revision = '76cd32cb1bb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_stim_aids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stim_aid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stim_aid_id'], ['stim_aids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_stim_aids')
    # ### end Alembic commands ###
