"""create stim aids table

Revision ID: 7b1c15c6123d
Revises: ea79602b7192
Create Date: 2022-03-15 17:38:24.974085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1c15c6123d'
down_revision = 'ea79602b7192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stim_aids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('noise_rating', sa.Integer(), nullable=True),
    sa.Column('chew_rating', sa.Integer(), nullable=True),
    sa.Column('texture_rating', sa.Integer(), nullable=True),
    sa.Column('consistency_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stim_aids')
    # ### end Alembic commands ###
