"""create stim aids tables

Revision ID: 31ddf44ce827
Revises: ea79602b7192
Create Date: 2022-03-25 13:29:12.216621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31ddf44ce827'
down_revision = 'ea79602b7192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stim_aids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.Text(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('noise_rating', sa.Integer(), nullable=True),
    sa.Column('chew_rating', sa.Integer(), nullable=True),
    sa.Column('texture_rating', sa.Integer(), nullable=True),
    sa.Column('consistency_rating', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_stim_aids',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stim_aid_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['stim_aid_id'], ['stim_aids.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'stim_aid_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_stim_aids')
    op.drop_table('stim_aids')
    # ### end Alembic commands ###
