"""create user special interests association table

Revision ID: 7b1c15c6123d
Revises: ea79602b7192
Create Date: 2022-03-15 17:25:39.755184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b1c15c6123d'
down_revision = 'ea79602b7192'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_special_interests',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('special_interest_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['special_interest_id'], ['special_interests.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'special_interest_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_special_interests')
    # ### end Alembic commands ###
